---

- name: "install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "Unarchive backend js files"
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: .

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present



- name: building node 
  become: true
  shell: |
      cd /home/ubuntu/backend
      npm run build
      npm run prestart:prod